name: JavaScript Automation
on:
  push:
    branches:
      - master
  pull_request:
    type: [opened, closed]

jobs:
  Test-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and Checkout Repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          npm test
